{{- if not .Values.database.persistentVolume.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "inventree.fullname" . }}-database
{{- with .Values.database.persistentVolume.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "inventree.labels" . | nindent 4 }}
spec:
{{- with .Values.database.persistentVolume.accessModes }}
  accessModes:
{{ toYaml . | indent 4 }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.database.persistentVolume.size | quote }}
{{- if .Values.database.persistentVolume.storageClass }}
  storageClassName: {{ .Values.database.persistentVolume.storageClass | quote }}
{{- end }}
{{- with .Values.database.persistentVolume.matchLabels }}
  selector:
    matchLabels:
      {{- toYaml . | nindent 6 }}
{{- end }}
{{- end }}
