apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventree.fullname" . }}-server
  labels:
    {{- include "inventree.labels" . | nindent 4 }}
data:
  INVENTREE_DB_ENGINE: mysql
  INVENTREE_DB_NAME: {{ include "inventree.fullname" . }}-database
  INVENTREE_SITE_URL: {{ .Values.global.siteUrl }}
  INVENTREE_DB_NAME: {{ .Values.database.name }}
  INVENTREE_DB_USER: root
  INVENTREE_DB_PASSWORD: ""
  INVENTREE_DB_HOST: {{ include "inventree.fullname" . }}-database
  INVENTREE_DEBUG: "True"
  INVENTREE_PLUGINS_ENABLED: "True"
  INVENTREE_AUTO_UPDATE: "True"


