apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventree.fullname" . }}-server
  labels:
    {{- include "inventree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "inventree.selectorLabels" . | nindent 4 }}
