apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inventree.fullname" . }}-worker
  labels:
    app: worker
    {{- include "inventree.labels" . | nindent 4 }}
spec:
# {{- if not .Values.autoscaling.enabled }}
# replicas: {{ .Values.replicaCount }}
# {{- end }}
  selector:
    matchLabels:
      app: worker
      {{- include "inventree.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: worker
        {{- include "inventree.labels" . | nindent 8 }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["invoke", "worker"]
          envFrom:
            - configMapRef:
                name: {{ include "inventree.fullname" . }}-server
          livenessProbe:
            {{- toYaml .Values.worker.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.worker.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /home/inventree/data
          {{- with .Values.worker.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ if .Values.global.persistentVolume.existingClaim }}{{ .Values.global.persistentVolume.existingClaim }}{{ else }}{{ include "inventree.fullname" . }}-data{{ end }}
      {{- with .Values.worker.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
